name: Typescript OpenAI Tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-typescript-openai-sdk:
    name: Typescript OpenAI SDK Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript-openai
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm install
      - run: npm test
